# Generated by Django 5.0 on 2024-12-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=250)),
                ("last_name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile_no", models.BigIntegerField(unique=True)),
                ("whatsapp_no", models.BigIntegerField(blank=True, null=True)),
                ("company_name", models.CharField(max_length=250)),
                ("registration_no", models.CharField(max_length=100)),
                ("vat_no", models.CharField(max_length=100)),
                ("address", models.TextField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("director", "Director"),
                            ("finance_manager", "Finance Manager"),
                            ("general_manager", "General Manager"),
                            ("user", "User"),
                        ],
                        max_length=50,
                    ),
                ),
                ("designation", models.CharField(max_length=250)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
